-- Migration 004: NULL-safe uniqueness for iso_serial_registry
-- Why: previous constraint UNIQUE (set_table, card_id, edition, parallel_name) fails to dedupe
--      when parallel_name is NULL (Postgres treats NULL as distinct). Result: multiple rows per
--      card when admin didn't set the parallel. This fix uses COALESCE so NULL == NULL for the
--      constraint, but the column still accepts NULL values.
--
-- IMPORTANT: Review the dup preview BEFORE running the cleanup block. Adjust the keep-row logic
-- if you disagree with "keep lowest id" (earliest row by insertion).

-- ───────────────────────────────────────────────────────────────────────────
-- STEP 1: Preview the dupes that will be merged (safe to run repeatedly)
-- ───────────────────────────────────────────────────────────────────────────
-- Run this first. It shows you every group of duplicate physical cards.
SELECT
  checklist_set_table,
  checklist_card_id,
  player,
  card_number,
  serial_edition,
  COALESCE(parallel_name, '(null)') AS parallel_key,
  COUNT(*) AS dup_count,
  array_agg(id ORDER BY id) AS row_ids,
  MIN(id) AS will_keep,
  array_agg(id ORDER BY id) FILTER (WHERE id > (SELECT MIN(id))) AS will_merge_and_delete
FROM iso_serial_registry
GROUP BY 1,2,3,4,5,6
HAVING COUNT(*) > 1
ORDER BY dup_count DESC, player;


-- ───────────────────────────────────────────────────────────────────────────
-- STEP 2: Merge + delete dupes (comment out if you only want to preview)
-- ───────────────────────────────────────────────────────────────────────────
-- Merges ownership_chain + price_history from all duplicates into the keep-row, then deletes the others.
BEGIN;

-- Build the merge payload: for each dup group, collect all chain entries + price entries
WITH dup_groups AS (
  SELECT
    checklist_set_table, checklist_card_id, serial_edition,
    COALESCE(parallel_name, '') AS pk,
    MIN(id) AS keep_id
  FROM iso_serial_registry
  GROUP BY 1,2,3,4
  HAVING COUNT(*) > 1
),
all_dup_rows AS (
  SELECT r.id, r.ownership_chain, r.price_history, dg.keep_id
  FROM iso_serial_registry r
  JOIN dup_groups dg
    ON r.checklist_set_table = dg.checklist_set_table
   AND r.checklist_card_id   = dg.checklist_card_id
   AND r.serial_edition      = dg.serial_edition
   AND COALESCE(r.parallel_name, '') = dg.pk
),
merged_chains AS (
  SELECT keep_id,
         jsonb_agg(DISTINCT elem ORDER BY elem) AS merged_chain
  FROM all_dup_rows
  CROSS JOIN LATERAL jsonb_array_elements(COALESCE(ownership_chain, '[]'::jsonb)) AS elem
  GROUP BY keep_id
),
merged_prices AS (
  SELECT keep_id,
         jsonb_agg(DISTINCT elem ORDER BY elem) AS merged_prices
  FROM all_dup_rows
  CROSS JOIN LATERAL jsonb_array_elements(COALESCE(price_history, '[]'::jsonb)) AS elem
  GROUP BY keep_id
)
UPDATE iso_serial_registry r
SET ownership_chain = COALESCE(mc.merged_chain, r.ownership_chain),
    price_history   = COALESCE(mp.merged_prices, r.price_history)
FROM merged_chains mc
LEFT JOIN merged_prices mp ON mp.keep_id = mc.keep_id
WHERE r.id = mc.keep_id;

-- Repoint any queue rows that pointed at the soon-to-be-deleted dupes to the keep-row
UPDATE iso_serial_queue q
SET linked_registry_id = dg.keep_id
FROM iso_serial_registry r
JOIN (
  SELECT
    checklist_set_table, checklist_card_id, serial_edition,
    COALESCE(parallel_name, '') AS pk,
    MIN(id) AS keep_id
  FROM iso_serial_registry
  GROUP BY 1,2,3,4
  HAVING COUNT(*) > 1
) dg
  ON r.checklist_set_table = dg.checklist_set_table
 AND r.checklist_card_id   = dg.checklist_card_id
 AND r.serial_edition      = dg.serial_edition
 AND COALESCE(r.parallel_name, '') = dg.pk
WHERE q.linked_registry_id = r.id
  AND r.id <> dg.keep_id;

-- Delete the dupes (keep only the MIN(id) per group)
DELETE FROM iso_serial_registry r
USING (
  SELECT
    checklist_set_table, checklist_card_id, serial_edition,
    COALESCE(parallel_name, '') AS pk,
    MIN(id) AS keep_id
  FROM iso_serial_registry
  GROUP BY 1,2,3,4
  HAVING COUNT(*) > 1
) dg
WHERE r.checklist_set_table = dg.checklist_set_table
  AND r.checklist_card_id   = dg.checklist_card_id
  AND r.serial_edition      = dg.serial_edition
  AND COALESCE(r.parallel_name, '') = dg.pk
  AND r.id <> dg.keep_id;

COMMIT;


-- ───────────────────────────────────────────────────────────────────────────
-- STEP 3: Swap the unique constraint for a NULL-safe version
-- ───────────────────────────────────────────────────────────────────────────
-- Drop the old constraint (name auto-generated by Postgres when created via UNIQUE(...))
ALTER TABLE iso_serial_registry
  DROP CONSTRAINT IF EXISTS iso_serial_registry_checklist_set_table_checklist_card_id_s_key;

-- Functional unique index: treats NULL parallel_name as empty string so NULL=NULL for the constraint.
-- The column itself can still be NULL; only the uniqueness check is NULL-safe.
CREATE UNIQUE INDEX IF NOT EXISTS iso_serial_registry_unique_physical
  ON iso_serial_registry (
    checklist_set_table,
    checklist_card_id,
    serial_edition,
    (COALESCE(parallel_name, ''))
  );
